# Generated by Django 5.2.17 on 2026-09-06 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('phase', models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR')], default='manual', max_length=20)),
                ('start_time', models.TimeField()),
                ('planned_end_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('attendance_ids', models.JSONField(blank=True, default=list)),
                ('marked_ids', models.JSONField(blank=True, default=list)),
                ('late_reason', models.CharField(blank=True, max_length=300)),
                ('is_auto_present', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ManyToManyField(related_name='attendance_sessions', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='teachers.teacher')),
                ('teaching_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='academics.teachingsession')),
            ],
            options={
                'ordering': ['-session_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='late', max_length=20)),
                ('marking', models.BooleanField(default=False)),
                ('marking_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['student__roll_no'],
                'constraints': [models.UniqueConstraint(fields=('attendance_session', 'student'), name='uniq_attendance_record_per_session_student')],
            },
        ),
        migrations.CreateModel(
            name='QRAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('token_generated_at', models.DateTimeField(auto_now_add=True)),
                ('student_ids', models.JSONField(blank=True, default=list)),
                ('student_timestamps', models.JSONField(blank=True, default=dict)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='attendance.attendancesession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked', False)), fields=('teacher',), name='uniq_active_qr_session_per_teacher')],
            },
        ),
    ]
