# Generated by Django 5.2.17 on 2026-09-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='bssid_normalized',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='network_verification_method',
            field=models.CharField(choices=[('bssid', 'BSSID'), ('mobile_network_bridge', 'Mobile network bridge'), ('unavailable', 'Unavailable')], default='unavailable', max_length=32),
        ),
    ]
