# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_bssid_normalized_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='bssid_normalized',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='network_verification_method',
            field=models.CharField(choices=[('unavailable', 'Unavailable')], default='unavailable', max_length=32),
        ),
    ]
